import { report } from "@/content/hub/one-hour-chicago";

/* LOVELEEDAY — ONE HOUR: Chicago, full analysis report.
   Local only, not deployed, no token — regenerated by loveleeday-command/lib/report.mjs from
   the real run's event log every time a run completes or a report is requested mid-run. */

function Eyebrow({ children }: { children: React.ReactNode }) {
  return <span className="block text-[10px] font-semibold uppercase tracking-[0.16em] text-[#7d8088]">{children}</span>;
}

function Two({ a, b }: { a: string; b: string }) {
  return (
    <h1 className="mt-4 font-medium text-[clamp(2.2rem,5vw,3.6rem)] leading-[1.05] tracking-[-0.045em] text-[#1d1d1f]">
      {a}
      <br />
      <span className="text-[#8c8e95]">{b}</span>
    </h1>
  );
}

const STATUS_CLS: Record<string, string> = {
  verified: "bg-[#e6f4ea] text-[#1e6b3a]",
  hypothesis: "bg-[#fff4e0] text-[#8a5a00]",
};

function Badge({ children, cls }: { children: React.ReactNode; cls: string }) {
  return <span className={`inline-block rounded-full px-2.5 py-1 text-[11px] font-medium ${cls}`}>{children}</span>;
}

/* Context → Data → Insight → Action: per the marketing brief, every finding that names a place
   or organization is written once in this shape and used both as a report section and an
   outreach packet — never a second, differently-worded version for outreach. */
function FindingCard({ f }: { f: any }) {
  const c = f.cdia || {};
  return (
    <div className="rounded-2xl border border-[#e4e5e9] bg-white p-5">
      <div className="text-[15px] font-semibold text-[#1d1d1f]">{f.title}</div>
      <div className="mt-3 space-y-2 text-[13px] leading-[1.65]">
        <div><span className="font-semibold text-[#7d8088]">Context — </span><span className="text-[#4a4d54]">{c.context}</span></div>
        <div><span className="font-semibold text-[#7d8088]">Data — </span><span className="text-[#4a4d54]">{c.data || f.summary}</span></div>
        <div><span className="font-semibold text-[#7d8088]">Insight — </span><span className="text-[#4a4d54]">{c.insight}</span></div>
        <div><span className="font-semibold text-[#7d8088]">Action — </span><span className="text-[#4a4d54]">{c.action}</span></div>
      </div>
      <div className="mt-3 flex flex-wrap items-center gap-2">
        <Badge cls={STATUS_CLS[f.status] || "bg-[#eef0f3] text-[#4a4f58]"}>{f.status}</Badge>
        <span className="text-[11px] uppercase tracking-wide text-[#9a9da4]">confidence {Math.round((f.confidence || 0) * 100)}%</span>
      </div>
      {f.evidence?.length ? (
        <div className="mt-3 space-y-1 border-t border-[#eef0f3] pt-3">
          {f.evidence.map((e: any, i: number) => (
            <a key={i} href={e.query} target="_blank" rel="noopener" className="block truncate text-[11px] text-[#0066cc] hover:underline">
              {e.description}
            </a>
          ))}
        </div>
      ) : null}
    </div>
  );
}

function SelfCheckSection({ sc }: { sc: any }) {
  const frozen = sc?.frozenDatasetCatch;
  const review = sc?.review;
  return (
    <section className="mx-auto max-w-[1080px] px-6 pb-16">
      <Eyebrow>PROOF THE SYSTEM CHECKS ITSELF</Eyebrow>
      <p className="mt-2 max-w-[70ch] text-[13px] text-[#7d8088]">
        These two beats matter more than any single finding above: they show the run catching its own errors and
        re-verifying its own numbers against live data, not just producing counts.
      </p>
      <div className="mt-4 grid gap-4 sm:grid-cols-2">
        <div className="rounded-2xl border-2 border-[#0066cc] bg-[#f0f6ff] p-5">
          <div className="text-[11px] font-semibold uppercase tracking-wide text-[#0066cc]">Frozen-dataset catch</div>
          {typeof frozen === "string" ? (
            <p className="mt-2 text-[14px] text-[#4a4d54]">{frozen}</p>
          ) : (
            <>
              <div className="mt-2 text-[15px] font-semibold text-[#1d1d1f]">{frozen.title}</div>
              <p className="mt-2 text-[13px] leading-[1.65] text-[#4a4d54]">{frozen.summary}</p>
              {frozen.sourceLink ? <a href={frozen.sourceLink} target="_blank" rel="noopener" className="mt-2 block text-[11px] text-[#0066cc] hover:underline">source query</a> : null}
            </>
          )}
        </div>
        <div className="rounded-2xl border-2 border-[#0066cc] bg-[#f0f6ff] p-5">
          <div className="text-[11px] font-semibold uppercase tracking-wide text-[#0066cc]">Live self-review tally</div>
          {typeof review === "string" ? (
            <p className="mt-2 text-[14px] text-[#4a4d54]">{review}</p>
          ) : (
            <p className="mt-2 text-[14px] leading-[1.65] text-[#4a4d54]">
              <span className="text-[20px] font-semibold tabular-nums text-[#1d1d1f]">{review.unchanged}/{review.total}</span> findings
              re-verified unchanged on a fresh live query, <span className="font-semibold text-[#1d1d1f]">{review.revised}</span> revised
              because the underlying city data moved, <span className="font-semibold text-[#1d1d1f]">{review.unrecheckable}</span> skipped.
            </p>
          )}
        </div>
      </div>
    </section>
  );
}

export default function OneHourChicagoReport() {
  const r: any = report;
  return (
    <div className="ll-os bg-white">
      <section className="mx-auto max-w-[1080px] px-6 pb-16 pt-16 sm:pt-24">
        <Eyebrow>LOVELEEDAY — ONE HOUR</Eyebrow>
        <Two a={r.meta?.command || "Run a case study analysis"} b={`${r.status} · ${r.meta?.target || r.meta?.city}`} />
        <p className="mt-6 max-w-[62ch] text-[17px] leading-[1.7] text-[#4a4d54]">
          A live intelligence run against {r.meta?.target || r.meta?.city}'s public open data ({r.meta?.domain || "data.cityofchicago.org"}) — every number below traces to a real, re-runnable query. Generated {new Date(r.generatedAt).toLocaleString()}.
        </p>
        <div className="mt-8 grid grid-cols-2 gap-4 sm:grid-cols-4 lg:grid-cols-8">
          {[
            ["sources", r.counters?.sources],
            ["rows retrieved", r.counters?.recordsProcessed],
            ["city records counted", r.counters?.recordsCovered],
            ["entities", r.entitiesCount],
            ["relationships", r.linksCount],
            ["hypotheses", r.counters?.hypotheses],
            ["findings", r.counters?.findings],
            ["verified", r.counters?.findingsVerified],
          ].map(([label, val]: any) => (
            <div key={label} className="rounded-xl border border-[#e4e5e9] bg-[#f5f5f7] p-3">
              <div className="text-[20px] font-semibold tabular-nums text-[#1d1d1f]">{(val ?? 0).toLocaleString()}</div>
              <div className="mt-1 text-[10px] uppercase tracking-wide text-[#7d8088]">{label}</div>
            </div>
          ))}
        </div>
        {r.milestones?.fullCompletion ? (
          <p className="mt-6 text-[14px] font-medium text-[#1e6b3a]">
            Complete in {(r.milestones.fullCompletion / 60000).toFixed(1)} minutes — 60:00 was the ceiling, not the target.
            {r.milestones.firstSource ? ` First source pulled at ${(r.milestones.firstSource / 1000).toFixed(0)}s.` : ""}
            {r.milestones.firstVerifiedFinding ? ` First verified finding at ${(r.milestones.firstVerifiedFinding / 1000).toFixed(0)}s.` : ""}
          </p>
        ) : null}
      </section>

      {r.checklist?.length ? (
        <section className="mx-auto max-w-[1080px] px-6 pb-16">
          <Eyebrow>COMPLETION CHECKLIST — LOCKED BEFORE THE CLOCK STARTED</Eyebrow>
          <div className="mt-4 divide-y divide-[#eef0f3] rounded-2xl border border-[#e4e5e9]">
            {r.checklist.map((c: any) => (
              <div key={c.id} className="flex items-center justify-between gap-4 px-5 py-3">
                <span className="text-[13px] text-[#1d1d1f]">{c.label}</span>
                <span className={`text-[11px] font-semibold uppercase tracking-wide ${c.done ? "text-[#1e6b3a]" : "text-[#9a9da4]"}`}>
                  {c.done ? "✓ cleared" : "not yet"}
                </span>
              </div>
            ))}
          </div>
        </section>
      ) : null}

      <section className="mx-auto max-w-[1080px] px-6 pb-16">
        <Eyebrow>TOP FINDINGS</Eyebrow>
        <div className="mt-4 grid gap-4 sm:grid-cols-3">
          {(r.topFindings || []).map((f: any) => <FindingCard key={f.id} f={f} />)}
        </div>
      </section>

      <SelfCheckSection sc={r.selfCheck} />

      {(r.missionOrder || []).map((m: string) => {
        const list = r.findingsByMission?.[m] || [];
        if (!list.length) return null;
        return (
          <section key={m} className="mx-auto max-w-[1080px] px-6 pb-16">
            <Eyebrow>{r.missionLabels?.[m] || m}</Eyebrow>
            <div className="mt-4 grid gap-4 sm:grid-cols-2">
              {list.map((f: any) => <FindingCard key={f.id} f={f} />)}
            </div>
          </section>
        );
      })}

      <section className="mx-auto max-w-[1080px] px-6 pb-16">
        <Eyebrow>THE COMMUNITY-AREA PICTURE</Eyebrow>
        <p className="mt-3 max-w-[70ch] text-[14px] leading-[1.7] text-[#4a4d54]">
          The {r.topAreas?.length || 0} most active geographic units in {r.meta?.target || r.meta?.city} this run resolved, by combined
          license and permit volume in the trailing 12 months.
        </p>
        <div className="mt-4 overflow-x-auto rounded-2xl border border-[#e4e5e9]">
          <table className="w-full text-left text-[13px]">
            <thead className="bg-[#f5f5f7] text-[11px] uppercase tracking-wide text-[#7d8088]">
              <tr><th className="px-4 py-2">Area</th><th className="px-4 py-2">New licenses</th><th className="px-4 py-2">Permits</th><th className="px-4 py-2">Hospitality</th></tr>
            </thead>
            <tbody>
              {(r.topAreas || []).map((a: any) => (
                <tr key={a.areaNum} className="border-t border-[#eef0f3]">
                  <td className="px-4 py-2 font-medium text-[#1d1d1f]">{a.name}</td>
                  <td className="px-4 py-2 tabular-nums">{a.stats?.recentLicenses ?? 0} <span className="text-[#9a9da4]">(vs {a.stats?.priorLicenses ?? 0})</span></td>
                  <td className="px-4 py-2 tabular-nums">{a.stats?.recentPermits ?? 0} <span className="text-[#9a9da4]">(vs {a.stats?.priorPermits ?? 0})</span></td>
                  <td className="px-4 py-2 tabular-nums">{a.stats?.recentHospitality ?? 0}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>

      <section className="mx-auto max-w-[1080px] px-6 pb-16">
        <Eyebrow>WHAT WE MISSED</Eyebrow>
        <div className="mt-4 grid gap-6 sm:grid-cols-2">
          <div>
            <div className="text-[12px] font-semibold uppercase tracking-wide text-[#8a5a00]">Datasets not yet pulled</div>
            <ul className="mt-2 space-y-1 text-[13px] text-[#4a4d54]">
              {(r.whatWeMissed?.datasetsNotPulled || []).map((d: any, i: number) => <li key={i}>{d.dataset} <span className="text-[#9a9da4]">({d.id})</span></li>)}
            </ul>
          </div>
          <div>
            <div className="text-[12px] font-semibold uppercase tracking-wide text-[#8a5a00]">Low-evidence areas, excluded</div>
            <ul className="mt-2 space-y-1 text-[13px] text-[#4a4d54]">
              {(r.whatWeMissed?.lowEvidenceAreas || []).slice(0, 10).map((a: any, i: number) => <li key={i}>{a.name}: {a.reason}</li>)}
            </ul>
          </div>
        </div>
        <p className="mt-4 max-w-[70ch] text-[13px] leading-[1.7] text-[#7d8088]">{r.whatWeMissed?.note}</p>
        {r.closingNote ? <p className="mt-2 max-w-[70ch] text-[13px] leading-[1.7] text-[#7d8088]">{r.closingNote}</p> : null}
      </section>

      {r.progress?.length ? (
        <section className="mx-auto max-w-[1080px] px-6 pb-16">
          <Eyebrow>PROGRESS CURVE — WHAT THE HOUR ACTUALLY DID, MINUTE BY MINUTE</Eyebrow>
          <div className="mt-4 overflow-x-auto rounded-2xl border border-[#e4e5e9]">
            <table className="w-full text-left text-[12px]">
              <thead className="bg-[#f5f5f7] text-[11px] uppercase tracking-wide text-[#7d8088]">
                <tr><th className="px-4 py-2">Minute</th><th className="px-4 py-2">Sources</th><th className="px-4 py-2">Entities</th><th className="px-4 py-2">Relationships</th><th className="px-4 py-2">Hypotheses</th><th className="px-4 py-2">Findings</th><th className="px-4 py-2">Verified</th></tr>
              </thead>
              <tbody>
                {r.progress.map((p: any, i: number) => (
                  <tr key={i} className="border-t border-[#eef0f3]">
                    <td className="px-4 py-2 tabular-nums">{p.minute}</td>
                    <td className="px-4 py-2 tabular-nums">{p.counters?.sources ?? 0}</td>
                    <td className="px-4 py-2 tabular-nums">{p.counters?.entities ?? 0}</td>
                    <td className="px-4 py-2 tabular-nums">{p.counters?.relationships ?? 0}</td>
                    <td className="px-4 py-2 tabular-nums">{p.counters?.hypotheses ?? 0}</td>
                    <td className="px-4 py-2 tabular-nums">{p.counters?.findings ?? 0}</td>
                    <td className="px-4 py-2 tabular-nums">{p.counters?.findingsVerified ?? 0}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </section>
      ) : null}

      <section className="mx-auto max-w-[1080px] px-6 pb-16">
        <Eyebrow>METHODOLOGY</Eyebrow>
        <p className="mt-3 max-w-[70ch] text-[14px] leading-[1.7] text-[#4a4d54]">
          Every count compares a trailing-12-month window to the prior 12 months, computed via live SoQL aggregate
          queries against {r.meta?.target || r.meta?.city}'s Socrata portal ({r.meta?.domain || "data.cityofchicago.org"}) — never fetched row-by-row and never
          cached across runs. A community area or category needs at least 8–15 prior-year occurrences (by dataset)
          before a percentage change is reported; below that floor it is listed as low-evidence and excluded. The
          top findings in each mission are additionally re-verified by re-issuing a narrower, subject-scoped query
          and confirming the count matches before being marked "verified" rather than "hypothesis". 60:00 is a
          ceiling, not a target: the run closes the instant its completion checklist clears (see above) — closing
          means a full closing Review pass, re-checking every finding this run produced against a fresh live query
          ({r.reviewChecksRun || 0} checks this run), never a re-check sprinkled in as filler during the analysis
          itself. The target's data portal was discovered live via Socrata's cross-domain catalog search — no
          per-target code or hardcoded dataset list — and every dataset role (date field, geography, category,
          owner) was inferred from its own real column names.
        </p>
      </section>

      {r.changeSinceLastRun?.hasPrevious ? (
        <section className="mx-auto max-w-[1080px] px-6 pb-16">
          <Eyebrow>WHAT CHANGED SINCE THE LAST RUN</Eyebrow>
          <p className="mt-2 text-[13px] text-[#7d8088]">Compared against run {r.changeSinceLastRun.previousRunId} ({new Date(r.changeSinceLastRun.previousAt).toLocaleString()}).</p>
          <div className="mt-4 grid gap-6 sm:grid-cols-3 text-[13px]">
            <div>
              <div className="font-semibold uppercase text-[11px] tracking-wide text-[#1e6b3a]">New findings ({r.changeSinceLastRun.added?.length || 0})</div>
              <ul className="mt-2 space-y-1 text-[#4a4d54]">{(r.changeSinceLastRun.added || []).map((f: any) => <li key={f.id}>{f.title}</li>)}</ul>
            </div>
            <div>
              <div className="font-semibold uppercase text-[11px] tracking-wide text-[#a1291f]">No longer findings ({r.changeSinceLastRun.removed?.length || 0})</div>
              <ul className="mt-2 space-y-1 text-[#4a4d54]">{(r.changeSinceLastRun.removed || []).map((f: any) => <li key={f.id}>{f.title}</li>)}</ul>
            </div>
            <div>
              <div className="font-semibold uppercase text-[11px] tracking-wide text-[#8a5a00]">Changed ({r.changeSinceLastRun.changed?.length || 0})</div>
              <ul className="mt-2 space-y-1 text-[#4a4d54]">{(r.changeSinceLastRun.changed || []).map((c: any, i: number) => <li key={i}>{c.before} → {c.after}</li>)}</ul>
            </div>
          </div>
        </section>
      ) : r.changeSinceLastRun ? (
        <section className="mx-auto max-w-[1080px] px-6 pb-16">
          <Eyebrow>WHAT CHANGED SINCE THE LAST RUN</Eyebrow>
          <p className="mt-2 text-[13px] text-[#7d8088]">No prior run stored for this target yet — this is the first snapshot.</p>
        </section>
      ) : null}

      <section className="mx-auto max-w-[1080px] px-6 pb-24">
        <Eyebrow>SOURCE REGISTER</Eyebrow>
        <div className="mt-4 overflow-x-auto rounded-2xl border border-[#e4e5e9]">
          <table className="w-full text-left text-[12px]">
            <thead className="bg-[#f5f5f7] text-[11px] uppercase tracking-wide text-[#7d8088]">
              <tr><th className="px-4 py-2">Pull</th><th className="px-4 py-2">Rows</th><th className="px-4 py-2">Covered</th><th className="px-4 py-2">Latency</th><th className="px-4 py-2">Query</th></tr>
            </thead>
            <tbody>
              {(r.sourcePulls || []).map((s: any, i: number) => (
                <tr key={i} className="border-t border-[#eef0f3] align-top">
                  <td className="px-4 py-2">{s.label}</td>
                  <td className="px-4 py-2 tabular-nums">{s.rowCount}</td>
                  <td className="px-4 py-2 tabular-nums">{s.coveredCount ? s.coveredCount.toLocaleString() : "—"}</td>
                  <td className="px-4 py-2 tabular-nums">{s.ms}ms</td>
                  <td className="px-4 py-2"><a href={s.url} target="_blank" rel="noopener" className="text-[#0066cc] hover:underline break-all">query</a></td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        <p className="mt-6 text-[11px] text-[#9a9da4]">
          Run {r.runId} · generated {new Date(r.generatedAt).toLocaleString()} · LOVELEEDAY, local-only report, not deployed.
        </p>
      </section>
    </div>
  );
}
