/* Delivery platforms review and game plan — LOVELEEDAY review. Generated by `review-page new dabney-delivery`.
   Sources, September 29, 2026: Toast orders by dining option (Jul 1 to Sep 29), DoorDash merchant portal (financials,
   campaigns, summary) and Uber Eats Manager (payouts, marketing, operations, offers) read headless with saved sessions,
   DoorDash weekly summary emails (Aug 24 to Sep 27), Grubhub and Uber merchant emails, Meta Marketing API.
   Builds on the Sept 26 ordering review (/p/dabney-ordering). Internal, local only. */
export type Sev = "fix" | "watch" | "good";

export const clients = [{ token: "dabney-delivery-internal", short: "Dabney & Co.", preparedFor: "Daniel May", role: "Owner" }];
export const getClient = (t: string) => clients.find((c) => c.token === t);

export const copy = {
  title: "Delivery platforms review and game plan",
  asOf: "September 29",
  hero: {
    a: "Delivery is paying for its own marketing.",
    b: "Cut the spend, fix the downtime, then grow.",
    intro: "We read the DoorDash and Uber Eats merchant portals, every DoorDash weekly summary since August and Toast's orders by platform for the last 90 days. DoorDash carries the channel, but marketing now takes 34 cents of every dollar it sells on top of a 21% commission. Uber Eats pays Uber more than it earns. Grubhub has sold $46 in six weeks.",
  },
  grades: { a: "Where each platform is today,", b: "and after the plan.", intro: "Struck-through grade is today; the bold one is after the fixes at the bottom." },
  model: { a: "How delivery should run,", b: "in four rules.", intro: "The platforms are a way to reach people who would not walk in. They are worth it only while each order still leaves money after commission, marketing and food." },
  fixes: { a: "The game plan,", b: "in order of dollars.", intro: "Two changes stop money leaving this week and need your go, because they change paid campaigns. The rest is free." },
};

export const glance: { k: string; label: string; src: string }[] = [
  { k: "34%", label: "of DoorDash sales went to DoorDash marketing in the last 30 days ($510 of $1,480), on top of $309 in commission and fees", src: "DoorDash merchant portal, payouts Sep 1 to Sep 22" },
  { k: "-$39", label: "Uber Eats total payout Sept 7 to 29: $66.50 of sales against $79.89 of Uber ads, $14.25 in fees and an $11.50 chargeback", src: "Uber Eats Manager, Payouts" },
  { k: "14 to 8", label: "DoorDash orders a week, from the week of Aug 31 to last week, while every campaign kept running", src: "DoorDash weekly summaries" },
  { k: "6 to 15%", label: "of open hours DoorDash showed the store as closed, every week since late August", src: "DoorDash weekly summaries, Downtime" },
];

export const table: { eyebrow: string; a: string; b: string; intro: string; columns: string[]; rows: string[][] } | null = {
  eyebrow: "The platforms side by side",
  a: "One platform works.",
  b: "Two cost more than they earn.",
  intro: "Orders and sales are Toast's count of delivery and platform pickup orders, Jul 1 to Sep 29. Marketing and fees are from each platform's own portal.",
  columns: ["Platform", "Orders (90 days)", "Sales", "Avg order", "Commission", "Marketing now", "Rating"],
  rows: [
    ["DoorDash", "146", "$3,959", "$27", "about 21% with fees", "3 campaigns, 34% of sales", "4.58 (Loved)"],
    ["Uber Eats", "14", "$454", "$32", "25% delivery, 7% pickup", "$10/day ad + Buy 1 get 1, more than sales", "No reviews"],
    ["Grubhub", "3", "$46", "$15", "full, prices not marked up", "none", "none"],
    ["Toast online ordering", "0", "$0", "—", "none (card fees only)", "nothing points to it", "—"],
  ],
};

export const grades: { area: string; grade: string; was?: string; why: string }[] = [
  { area: "DoorDash", was: "C+", grade: "B+", why: "Real volume, a 4.58 rating and cheap new-customer promos that work (9.36x on the new-customer discount). Held back by an always-on ad to all customers, 6 to 15% weekly downtime and a 5-minute avoidable wait." },
  { area: "Uber Eats", was: "F", grade: "C", why: "One order in three weeks, a 100% error rate that week with an $11.50 chargeback, no reviews, and an ad that costs more than the store sells. Worth keeping live only with no paid marketing until reviews exist." },
  { area: "Grubhub", was: "F", grade: "—", why: "$20.67 in its first month, three orders in six weeks, priced like dine-in so full commission comes out of menu price. Close it." },
  { area: "Order size", was: "C", grade: "B", why: "A DoorDash order averages $27, one sandwich and a side. A dinner bundle and the Peach Cobbler Cornbread as the add-on can move it toward $35." },
  { area: "Measurement", was: "D", grade: "B", why: "The one Meta delivery ad ($44.88, Jul 2 to Aug 13, 159 clicks) cannot be tied to an order, and Toast's Take Out option is full of late-night bar tabs, which hides real takeout." },
];

export const findings: { sev: Sev; area: string; t: string; d: string }[] = [
  { sev: "fix", area: "DoorDash marketing", t: "DoorDash marketing takes 34% of sales, and orders fell anyway.", d: "Last five payouts: $1,479.50 sales, $308.57 commission and fees, $509.86 marketing, $661.07 kept. Three campaigns run with no end date: Advertise to customers ($448 spent, 3.77x), Discount for customers ($78, 9.36x, 13 new customers) and Smart Promo credit ($353, 4.31x, 45 new customers). DoorDash credits them with $3,750 of sales in 90 days, which is nearly every DoorDash order, including repeat customers who would have ordered anyway. Weekly orders still went from 14 to 8." },
  { sev: "fix", area: "Margin per order", t: "After commission and marketing, a $27 DoorDash order leaves about $12 to pay for the food.", d: "21% commission ($5.70) plus 34% marketing ($9.20) leaves about $12.10. At a typical 30% food cost ($8.10, an assumption, not measured) that is about $4 before packaging and labor. At 12% marketing it would be about $10." },
  { sev: "fix", area: "Uber Eats", t: "Uber Eats is costing money: marketing alone exceeds sales.", d: "An Uber ad has run since Jul 24 at up to $10 a day, and a Buy 1 get 1 offer runs to Jul 2027. Sept 7 to 29: $79.89 of marketing, $66.50 of sales from one order, a $11.50 chargeback on that order, and a total payout of -$39.14. On 13 days with no sales the store still paid $2 to $10." },
  { sev: "fix", area: "Downtime", t: "DoorDash shows the store closed for 6 to 15% of open hours every week.", d: "15.1% the week of Sep 14, 12.7% the week before, 3.2% last week. A closed store loses the order and slips in DoorDash ranking. Avoidable wait (a driver waiting on food) ran 2 to 5 minutes and is flagged Needs attention. Uber Eats was paused by staff several times between Jul 29 and Aug 4, and offline for days." },
  { sev: "fix", area: "Grubhub", t: "Grubhub has earned $46 in six weeks.", d: "Live since Aug 17. Three orders, $20.67 in its first month. Toast cannot mark up Grubhub prices, so each order pays full commission out of dine-in pricing." },
  { sev: "watch", area: "Toast data", t: "Toast's Take Out option is full of bar tabs.", d: "200 orders in 90 days, mostly shots and cocktails rung between 10 PM and midnight. Real food takeout is invisible in reports until bar tabs go back under Dine In." },
  { sev: "good", area: "What works", t: "DoorDash's new-customer promos and the food itself.", d: "The new-customer discount returned $9.36 per dollar and the Smart Promo credit found 45 new customers. The DoorDash rating is 4.58 with recent reviews like Excellent quality and Flavorful. The top sellers travel well: Sunday Dinner Sandwich, Fried Green Tomato BLT, Peach Cobbler Cornbread, Collard Green Dip." },
];

export const model: { t: string; d: string }[] = [
  { t: "Marketing stays under 15% of platform sales", d: "Checked every Monday from the payout table. Above it, the order stops paying for its food." },
  { t: "Pay to find new customers, not to reach old ones", d: "New-customer discounts and credits earn their cost. An ad shown to everyone mostly buys orders that would have come anyway." },
  { t: "No paid marketing on a platform with no reviews", d: "An ad sends people to a store with nothing to reassure them. Earn the first reviews with the bag card, then advertise." },
  { t: "Every platform price covers its commission", d: "DoorDash already adds $1.50 an item. Uber Eats should match it, and a platform that cannot mark up, like Grubhub, does not stay." },
];

export const fixes: { t: string; d: string; tag: "done" | "free" | "needs" | "money" }[] = [
  { tag: "needs", t: "Pause the Uber Eats ad.", d: "It spends up to $10 a day for about one order in three weeks. Pausing saves roughly $80 to $100 a month and can be resumed any time. Your go needed because it changes a paid campaign." },
  { tag: "needs", t: "Pause DoorDash's Advertise to customers; keep the two new-customer promos with a weekly cap.", d: "Cuts DoorDash marketing from about $500 a month toward $150 while keeping the campaigns that bring new customers. Watch weekly orders for three weeks; if they drop more than two a week, bring the ad back with a $25 weekly cap." },
  { tag: "free", t: "Fix downtime before spending on growth.", d: "Match DoorDash and Uber hours to kitchen hours, keep the tablet on and charged, and use longer prep times instead of pausing on busy nights. Target under 2% downtime and under 2 minutes of avoidable wait." },
  { tag: "needs", t: "Close Grubhub.", d: "Three orders in six weeks at dine-in prices with full commission. Nothing is lost by closing it." },
  { tag: "free", t: "Add a dinner-for-two bundle and a cornbread add-on on DoorDash.", d: "Sunday Dinner Sandwich, Collard Green Dip and Peach Cobbler Cornbread together, priced near $38, to lift the $27 average order." },
  { tag: "free", t: "Put a bag card in every delivery bag.", d: "Asks for a rating on the platform the order came from. Uber Eats needs its first reviews before any ad can work." },
  { tag: "free", t: "Match Uber Eats pricing to DoorDash's markup.", d: "Uber Eats Manager's Menu pricing asks for the in-store menu; set the same +$1.50 an item DoorDash uses so commission is covered." },
  { tag: "free", t: "Move bar tabs out of Toast's Take Out option.", d: "So takeout reports show food, and each platform can be judged on its own numbers." },
  { tag: "done", t: "Headless access to DoorDash and Uber Eats saved.", d: "doordash-merchant-pull.mjs and ubereats-manager-pull.mjs read both portals without a browser window; the Monday check can run on its own. Grubhub still needs a sign-in each time." },
];

export const method: string[] = [
  "Toast orders API, Jul 1 to Sep 29, 2026, grouped by dining option (toast-channel-report.mjs): DoorDash Delivery and Takeout, Uber Eats Delivery and Takeout, Grubhub Delivery.",
  "DoorDash merchant portal, store 45827745, read Sep 29: payouts for the last 30 days (sales, commission and fees, marketing spend, net), Campaigns for the last 90 days, summary rating.",
  "DoorDash weekly summary emails, weeks of Aug 24 through Sep 21: gross sales, orders, average ticket, avoidable wait, downtime, cancellations.",
  "Uber Eats Manager, store ca976632, read Sep 29: payouts Sep 7 to 29 with pay breakdown and fee rates, marketing campaigns, operations (errors and chargebacks), offers and ads pages, menu pricing.",
  "Uber Eats shop-status emails Jul 29 to Aug 4; Grubhub merchant emails including the first-month summary (Sep 16).",
  "Meta Marketing API: [FOOD] Dabney Delivery — Order Today, Jul 2 to Aug 13, 2026.",
  "Food cost of 30% in the margin example is an assumption for illustration, not a measured Dabney figure.",
];
