/* Instagram feed review and redesign — LOVELEEDAY review. Generated by `review-page new dabney-instagram`.
   Every figure is from the Instagram Graph API pull of @dabneyandco on September 29, 2026 (ig-feed-audit.mjs). Internal, local only. */
export type Sev = "fix" | "watch" | "good";

export const clients = [{ token: "dabney-instagram-internal", short: "Dabney & Co.", preparedFor: "Daniel May", role: "Owner" }];
export const getClient = (t: string) => clients.find((c) => c.token === t);

export const copy = {
  title: "Instagram feed review and redesign",
  asOf: "September 29",
  hero: {
    a: "The feed is a flyer board.",
    b: "The room people come for is not on it.",
    intro: "We pulled all 24 posts on @dabneyandco with their reach, saves, shares and interactions, rebuilt the grid the way a visitor sees it, and compared what each kind of post earns. The short answer: the live-music poster works, but it now fills most of the grid, not one post shows the room or the people in it, and the two formats that travel furthest (reels and carousels) are three posts out of 24.",
  },
  grades: { a: "Where the feed is today,", b: "and after the fixes.", intro: "Struck-through grade is today; the bold one is after the fixes at the bottom." },
  model: { a: "Three posts a night,", b: "one column each.", intro: "Every named night gets a poster, a real photo of the room, and a reel, posted in that order so the poster announces first and each lands in its own column of the grid." },
  fixes: { a: "Done so far,", b: "and what is left.", intro: "The No Skips post is ready for your approval, the archive list needs five minutes in the Instagram app, and two short reels need to be filmed at the bar." },
};

export const glance: { k: string; label: string; src: string }[] = [
  { k: "24", label: "posts in 14 months, with silences from July 2025 to January 2026 and February to June 2026", src: "Instagram Graph API, Sept 29" },
  { k: "0", label: "posts that show the bar, the room or the guests", src: "Grid review, all 24 posts" },
  { k: "702 vs 537", label: "median reach of a reel against an event flyer; reels also earn about three times the shares", src: "Per-post insights, posts before Sept 27" },
  { k: "7", label: "posts to archive: expired holidays, a 2025 Restaurant Week reel, and repeats", src: "Grid review" },
];

export const table: { eyebrow: string; a: string; b: string; intro: string; columns: string[]; rows: string[][] } | null = {
  eyebrow: "What each kind of post earns",
  a: "Motion travels.",
  b: "Holidays don't.",
  intro: "Medians across posts older than two days, so the newest two are not counted before they have finished reaching people.",
  columns: ["Kind of post", "Posts", "Median reach", "Median interactions", "Shares per post"],
  rows: [
    ["Carousel (Blues Fest)", "1", "873", "52", "12"],
    ["Reels", "2", "702", "46", "12"],
    ["Event flyers", "11", "537", "41", "4.5"],
    ["Drink and food photos", "5", "387", "28", "2.6"],
    ["Holiday posts (Juneteenth, Father's Day)", "3", "329", "8", "2"],
  ],
};

export const grades: { area: string; grade: string; was?: string; why: string }[] = [
  { area: "Brand consistency", was: "C", grade: "B+", why: "The live-music poster is recognizable, but eight other styles sit beside it (After Dark teal, Off the Clock, the Maze flyer, Gospel Brunch, Juneteenth, Father's Day, pumpkin spice). A fixed three-column system gives every style one job and one place." },
  { area: "What the feed shows", was: "D", grade: "B", why: "17 of 24 posts are graphics and none shows the room. Real photos already exist: the bar, a full room on a live night, the lounge, performers, a couple toasting under the portrait wall." },
  { area: "Motion", was: "D", grade: "B", why: "Two reels in 14 months, both among the best performers. One filmed reel per named night fixes it." },
  { area: "Announcing nights", was: "B", grade: "A-", why: "Posters already carry the act, the date and the time, the shape the ads review found cheapest. Posting them 10 to 14 days out, not the week of, lets the organic post do the work the ads are paying for." },
  { area: "Freshness", was: "C", grade: "A", why: "Seven posts are expired or repeated. Archiving them is reversible and takes minutes." },
];

export const grids = {
  eyebrow: "The grid",
  a: "Today's feed,",
  b: "and the next two nights done right.",
  intro: "Both grids use the 3:4 crop Instagram's profile shows. Red chips mark the posts to archive. In the redesign, green tiles are ready now from real files, orange tiles need a 15-second clip filmed at the bar, and the dimmed rows are the posts already on the feed.",
  items: [
    { src: "/review/dabney-instagram/ig-before.jpg", caption: "Today: all 24 posts, newest first, with the seven to archive marked." },
    { src: "/review/dabney-instagram/ig-after.jpg", caption: "Redesign: No Skips and Homecoming, each as reel, room photo and poster, on top of the existing feed." },
  ],
};

export const findings: { sev: Sev; area: string; t: string; d: string }[] = [
  { sev: "fix", area: "The room", t: "No post on the feed shows the bar, the room or the people in it.", d: "17 of 24 posts are graphics and 5 are drinks or food. The website already carries real photos of the bar at night, a full room during a live set, the lounge corner, performers mid-song and a couple toasting under the portrait wall. None has ever been posted. A guest deciding where to go on Saturday cannot see what the night looks like." },
  { sev: "fix", area: "Motion", t: "Reels and the carousel reach the most people, and there are three of them.", d: "Median reach 702 for reels and 873 for the Blues Fest carousel, against 537 for an event flyer; both earn about 12 shares a post against 4.5. The Maize reel drew 18 shares, the most on the account." },
  { sev: "fix", area: "Archive", t: "Seven posts are expired, dated or repeated.", d: "Juneteenth (Jun 19, reach 329, 8 interactions), both Father's Day posts (Jun 18 and Jun 12), the Restaurant Week reel that still says \"starts July 17\" from 2025, the Aug 11 After Dark flyer that repeats the Sept 12 one, the Maize drink still that the Maize reel already covers, and the delivery flatbread (Jul 24, reach 264, 5 interactions). Archiving hides a post without deleting it, and it can be restored any time." },
  { sev: "fix", area: "No Skips video", t: "The No Skips promo video is cut from another company's performance footage.", d: "Frames at 5 and 9 seconds are studio performance footage of Kehlani and a second artist that Dabney does not own. Posted as a reel, it risks being muted or taken down and puts copyrighted footage in a promotion. The reel slot is marked to film instead: 15 seconds of the room or a pour at the bar." },
  { sev: "fix", area: "Grid crop", t: "The profile grid clips the sides of 4:5 posters.", d: "Instagram shows the middle 3:4 of each post on the profile, which cuts about 34 pixels off each side of a 1080-wide poster. On the Homecoming poster that clips the left edge of the vertical wordmark in the grid view. Keep type and faces at least 40 pixels in from the sides." },
  { sev: "watch", area: "Cadence", t: "The account went quiet twice for four to six months.", d: "July 2025 to January 2026, then February to June 2026. Since August it has posted 16 times, which is the right pace; the three-post rhythm keeps it there without extra work." },
  { sev: "good", area: "Live series", t: "The Live at Dabney poster is the account's signature, and it performs.", d: "Black-and-white portrait, gold letterboard, act, date and time. Event flyers hold a median reach of 537, and Shamara Allen's reached 942, the best single post. It keeps its own column in the redesign." },
];

export const model: { t: string; d: string }[] = [
  { t: "Every named night gets three posts", d: "The poster first, 10 to 14 days out; a real photo of the room two days later; a 15-second reel filmed at Dabney two days before the night. Posted in that order, the reel lands in the left column, the room in the middle and the poster on the right, so the grid reads as a system instead of a stack of flyers." },
  { t: "Real photos only in the middle column", d: "The bar, the room, the people, the food, all from the library of real Dabney photography. Never a generated room: an invented angle of a real place is never accurate." },
  { t: "Reels are filmed at Dabney", d: "Fifteen seconds, sound on: a pour, the room filling, the first song of the set. No artist footage from elsewhere, which is the one thing that can get a post taken down." },
  { t: "Archive what has aged", d: "Holiday and single-date promos come off the grid once they pass, unless they were among the best performers, like the Blues Fest carousel, which stays as proof of the signature event." },
];

export const fixes: { t: string; d: string; tag: "done" | "free" | "needs" | "money" }[] = [
  { tag: "needs", t: "Post No Skips to Instagram and Facebook.", d: "The 1080x1350 poster and the written caption are ready, and a dry run on Instagram passed. It goes out on your approval in chat." },
  { tag: "needs", t: "Archive the seven posts marked in red.", d: "Instagram's API cannot archive posts, so it is five minutes in the app: open the post, tap the three dots, Archive. Every one can be restored from the Archive tab." },
  { tag: "needs", t: "Film two 15-second reels at the bar.", d: "No Skips by Oct 1 (the room or a pour), Homecoming by Oct 8. A phone clip on a busy night is enough." },
  { tag: "free", t: "Post the room photos on the schedule in the grid.", d: "The bar on Sept 30 and the date-night photo on Oct 6, both from the real photo library, with short captions that point to the reservation link." },
  { tag: "free", t: "Keep poster type 40 pixels in from the sides.", d: "So the grid crop never clips a wordmark or a face again." },
  { tag: "done", t: "Feed pull and grid mockup tools built.", d: "ig-feed-audit.mjs pulls every post with its insights and draws the grid; ig-grid-mock.py renders any proposed grid from real files. Both rerun in a minute." },
];

export const method: string[] = [
  "Instagram Graph API, @dabneyandco (IG user 17841453471479670), all posts pulled September 29, 2026 with reach, saved, shares, total_interactions and, for reels, views.",
  "Comparisons by kind of post use medians of posts published before September 27, so the two newest posts are not judged before they finish reaching people.",
  "Real photo library: dabneyandco.com public images (the root folder, not _generated-do-not-use).",
  "No Skips video: ~/Documents/Dabney/Creative/2026-10-03-no-skips/live-at-dabney-no-skips-1003.mp4, sampled at 1, 5, 9 and 13 seconds.",
  "Grid mockups use the 3:4 center crop the Instagram profile grid applies to 4:5 and 9:16 posts.",
];
