// AUTO-GENERATED by loveleeday-command/lib/report.mjs — regenerated on every run.
// Local-only report content, not deployed, not in public/. Source of truth: the run's own
// event log at /Users/danielmay/Projects/loveleeday-command/runs/42cb397c/events.jsonl.
export const report = {
  "runId": "42cb397c",
  "generatedAt": "2026-09-29T03:18:21.224Z",
  "meta": {
    "city": "Chicago",
    "target": "Chicago",
    "domain": "data.cityofchicago.org",
    "kind": "city",
    "minutes": 1,
    "command": "Run a case study analysis of Chicago",
    "startedAt": 1790651829730
  },
  "status": "complete",
  "counters": {
    "sources": 22,
    "recordsProcessed": 916,
    "recordsCovered": 1248035,
    "entities": 0,
    "relationships": 0,
    "hypotheses": 1,
    "findings": 5,
    "findingsVerified": 5,
    "elapsedMs": 71270,
    "costUsd": 0
  },
  "entitiesCount": 0,
  "linksCount": 0,
  "findingsByMission": {
    "economic": [],
    "business_opportunity": [],
    "government": [],
    "neighborhood": [],
    "discoveries": [
      {
        "type": "finding",
        "mission": "discoveries",
        "id": "generic-stale-e68t-c7fv",
        "title": "Dataset found but frozen: COVID-19 Daily Rolling Average Case, Death, and Hospitalization Rates - Historical",
        "summary": "1,525 rows, but the newest record is dated 2024-05-16 — 866 days old. Excluded from trend analysis rather than silently treated as current.",
        "status": "verified",
        "confidence": 1,
        "evidence": [
          {
            "query": "https://data.cityofchicago.org/resource/e68t-c7fv.json?%24select=max%28date%29+as+latest",
            "description": "max(date) probe against the live dataset"
          }
        ],
        "relatedEntity": null,
        "metrics": {
          "recheckQuery": "https://data.cityofchicago.org/resource/e68t-c7fv.json?%24select=max%28date%29+as+latest",
          "recheckValueAtRunTime": "2024-05-16T00:00:00.000",
          "recheckDescription": "dataset's own latest date (won't move if truly frozen)"
        },
        "ts": 1790651858059,
        "reviewStatus": "reverified",
        "cdia": {
          "context": "discoveries mission — Dataset found but frozen: COVID-19 Daily Rolling Average Case, Death, and Hospitalization Rates - Historical",
          "data": "1,525 rows, but the newest record is dated 2024-05-16 — 866 days old. Excluded from trend analysis rather than silently treated as current.",
          "insight": "A pattern or a data-quality issue surfaced that wasn't part of the original mission brief.",
          "action": "Route to the research desk before quoting this dataset again; verify freshness first.",
          "sourceLink": "https://data.cityofchicago.org/resource/e68t-c7fv.json?%24select=max%28date%29+as+latest"
        }
      },
      {
        "type": "finding",
        "mission": "discoveries",
        "id": "generic-stale-7nii-7srd",
        "title": "Dataset found but frozen: 311 Service Requests - Vacant and Abandoned Buildings Reported - Historical",
        "summary": "65,119 rows, but the newest record is dated 2018-12-17 — 2843 days old. Excluded from trend analysis rather than silently treated as current.",
        "status": "verified",
        "confidence": 1,
        "evidence": [
          {
            "query": "https://data.cityofchicago.org/resource/7nii-7srd.json?%24select=max%28date_service_request_was_received%29+as+latest",
            "description": "max(date) probe against the live dataset"
          }
        ],
        "relatedEntity": null,
        "metrics": {
          "recheckQuery": "https://data.cityofchicago.org/resource/7nii-7srd.json?%24select=max%28date_service_request_was_received%29+as+latest",
          "recheckValueAtRunTime": "2018-12-17T00:00:00.000",
          "recheckDescription": "dataset's own latest date (won't move if truly frozen)"
        },
        "ts": 1790651871433,
        "reviewStatus": "reverified",
        "cdia": {
          "context": "discoveries mission — Dataset found but frozen: 311 Service Requests - Vacant and Abandoned Buildings Reported - Historical",
          "data": "65,119 rows, but the newest record is dated 2018-12-17 — 2843 days old. Excluded from trend analysis rather than silently treated as current.",
          "insight": "A pattern or a data-quality issue surfaced that wasn't part of the original mission brief.",
          "action": "Route to the research desk before quoting this dataset again; verify freshness first.",
          "sourceLink": "https://data.cityofchicago.org/resource/7nii-7srd.json?%24select=max%28date_service_request_was_received%29+as+latest"
        }
      },
      {
        "type": "finding",
        "mission": "discoveries",
        "id": "generic-stale-553k-3xzc",
        "title": "Dataset found but frozen: COVID-19 Vaccinations by ZIP Code - Historical",
        "summary": "65,160 rows, but the newest record is dated 2023-09-13 — 1112 days old. Excluded from trend analysis rather than silently treated as current.",
        "status": "verified",
        "confidence": 1,
        "evidence": [
          {
            "query": "https://data.cityofchicago.org/resource/553k-3xzc.json?%24select=max%28date%29+as+latest",
            "description": "max(date) probe against the live dataset"
          }
        ],
        "relatedEntity": null,
        "metrics": {
          "recheckQuery": "https://data.cityofchicago.org/resource/553k-3xzc.json?%24select=max%28date%29+as+latest",
          "recheckValueAtRunTime": "2023-09-13T00:00:00.000",
          "recheckDescription": "dataset's own latest date (won't move if truly frozen)"
        },
        "ts": 1790651873069,
        "reviewStatus": "reverified",
        "cdia": {
          "context": "discoveries mission — Dataset found but frozen: COVID-19 Vaccinations by ZIP Code - Historical",
          "data": "65,160 rows, but the newest record is dated 2023-09-13 — 1112 days old. Excluded from trend analysis rather than silently treated as current.",
          "insight": "A pattern or a data-quality issue surfaced that wasn't part of the original mission brief.",
          "action": "Route to the research desk before quoting this dataset again; verify freshness first.",
          "sourceLink": "https://data.cityofchicago.org/resource/553k-3xzc.json?%24select=max%28date%29+as+latest"
        }
      },
      {
        "type": "finding",
        "mission": "discoveries",
        "id": "generic-stale-3h7q-7mdb",
        "title": "Dataset found but frozen: Violence Reduction - Shotspotter Alerts - Historical",
        "summary": "222,108 rows, but the newest record is dated 2024-09-22 — 736 days old. Excluded from trend analysis rather than silently treated as current.",
        "status": "verified",
        "confidence": 1,
        "evidence": [
          {
            "query": "https://data.cityofchicago.org/resource/3h7q-7mdb.json?%24select=max%28date%29+as+latest",
            "description": "max(date) probe against the live dataset"
          }
        ],
        "relatedEntity": null,
        "metrics": {
          "recheckQuery": "https://data.cityofchicago.org/resource/3h7q-7mdb.json?%24select=max%28date%29+as+latest",
          "recheckValueAtRunTime": "2024-09-22T23:54:22.000",
          "recheckDescription": "dataset's own latest date (won't move if truly frozen)"
        },
        "ts": 1790651880706,
        "reviewStatus": "reverified",
        "cdia": {
          "context": "discoveries mission — Dataset found but frozen: Violence Reduction - Shotspotter Alerts - Historical",
          "data": "222,108 rows, but the newest record is dated 2024-09-22 — 736 days old. Excluded from trend analysis rather than silently treated as current.",
          "insight": "A pattern or a data-quality issue surfaced that wasn't part of the original mission brief.",
          "action": "Route to the research desk before quoting this dataset again; verify freshness first.",
          "sourceLink": "https://data.cityofchicago.org/resource/3h7q-7mdb.json?%24select=max%28date%29+as+latest"
        }
      },
      {
        "type": "finding",
        "mission": "discoveries",
        "id": "generic-stale-2vhs-cf6b",
        "title": "Dataset found but frozen: COVID-19 Daily Vaccinations - Chicago Residents - Historical",
        "summary": "1,003 rows, but the newest record is dated 2023-09-13 — 1112 days old. Excluded from trend analysis rather than silently treated as current.",
        "status": "verified",
        "confidence": 1,
        "evidence": [
          {
            "query": "https://data.cityofchicago.org/resource/2vhs-cf6b.json?%24select=max%28date%29+as+latest",
            "description": "max(date) probe against the live dataset"
          }
        ],
        "relatedEntity": null,
        "metrics": {
          "recheckQuery": "https://data.cityofchicago.org/resource/2vhs-cf6b.json?%24select=max%28date%29+as+latest",
          "recheckValueAtRunTime": "2023-09-13T00:00:00.000",
          "recheckDescription": "dataset's own latest date (won't move if truly frozen)"
        },
        "ts": 1790651883969,
        "reviewStatus": "reverified",
        "cdia": {
          "context": "discoveries mission — Dataset found but frozen: COVID-19 Daily Vaccinations - Chicago Residents - Historical",
          "data": "1,003 rows, but the newest record is dated 2023-09-13 — 1112 days old. Excluded from trend analysis rather than silently treated as current.",
          "insight": "A pattern or a data-quality issue surfaced that wasn't part of the original mission brief.",
          "action": "Route to the research desk before quoting this dataset again; verify freshness first.",
          "sourceLink": "https://data.cityofchicago.org/resource/2vhs-cf6b.json?%24select=max%28date%29+as+latest"
        }
      }
    ]
  },
  "missionOrder": [
    "economic",
    "business_opportunity",
    "government",
    "neighborhood",
    "discoveries"
  ],
  "missionLabels": {
    "economic": "Economic — license velocity by community area",
    "business_opportunity": "Business opportunity — where construction is outrunning supply",
    "government": "Government — service load and ridership",
    "neighborhood": "Neighborhood — the 77 community areas",
    "discoveries": "Discoveries — nobody asked for these"
  },
  "topFindings": [
    {
      "type": "finding",
      "mission": "discoveries",
      "id": "generic-stale-e68t-c7fv",
      "title": "Dataset found but frozen: COVID-19 Daily Rolling Average Case, Death, and Hospitalization Rates - Historical",
      "summary": "1,525 rows, but the newest record is dated 2024-05-16 — 866 days old. Excluded from trend analysis rather than silently treated as current.",
      "status": "verified",
      "confidence": 1,
      "evidence": [
        {
          "query": "https://data.cityofchicago.org/resource/e68t-c7fv.json?%24select=max%28date%29+as+latest",
          "description": "max(date) probe against the live dataset"
        }
      ],
      "relatedEntity": null,
      "metrics": {
        "recheckQuery": "https://data.cityofchicago.org/resource/e68t-c7fv.json?%24select=max%28date%29+as+latest",
        "recheckValueAtRunTime": "2024-05-16T00:00:00.000",
        "recheckDescription": "dataset's own latest date (won't move if truly frozen)"
      },
      "ts": 1790651858059,
      "reviewStatus": "reverified",
      "cdia": {
        "context": "discoveries mission — Dataset found but frozen: COVID-19 Daily Rolling Average Case, Death, and Hospitalization Rates - Historical",
        "data": "1,525 rows, but the newest record is dated 2024-05-16 — 866 days old. Excluded from trend analysis rather than silently treated as current.",
        "insight": "A pattern or a data-quality issue surfaced that wasn't part of the original mission brief.",
        "action": "Route to the research desk before quoting this dataset again; verify freshness first.",
        "sourceLink": "https://data.cityofchicago.org/resource/e68t-c7fv.json?%24select=max%28date%29+as+latest"
      }
    }
  ],
  "topAreas": [],
  "sourcePulls": [
    {
      "label": "Target resolved: Chicago → data.cityofchicago.org",
      "url": "https://api.us.socrata.com/api/catalog/v1?q=Chicago&limit=40",
      "rowCount": 2,
      "coveredCount": 0,
      "ms": 0
    },
    {
      "label": "Boundaries - Neighborhoods — geography reference",
      "url": "https://data.cityofchicago.org/resource/bbvz-uum9.json?%24select=count%28*%29+as+cnt",
      "rowCount": 98,
      "coveredCount": 0,
      "ms": 0
    },
    {
      "label": "data.cityofchicago.org catalog page",
      "url": "https://api.us.socrata.com/api/catalog/v1?domains=data.cityofchicago.org&limit=200&offset=0",
      "rowCount": 200,
      "coveredCount": 0,
      "ms": 0
    },
    {
      "label": "data.cityofchicago.org catalog page",
      "url": "https://api.us.socrata.com/api/catalog/v1?domains=data.cityofchicago.org&limit=200&offset=200",
      "rowCount": 200,
      "coveredCount": 0,
      "ms": 0
    },
    {
      "label": "data.cityofchicago.org catalog page",
      "url": "https://api.us.socrata.com/api/catalog/v1?domains=data.cityofchicago.org&limit=200&offset=400",
      "rowCount": 200,
      "coveredCount": 0,
      "ms": 0
    },
    {
      "label": "data.cityofchicago.org catalog page",
      "url": "https://api.us.socrata.com/api/catalog/v1?domains=data.cityofchicago.org&limit=200&offset=600",
      "rowCount": 200,
      "coveredCount": 0,
      "ms": 0
    },
    {
      "label": "City-Owned Land Inventory — profiled, no time dimension",
      "url": "https://data.cityofchicago.org/resource/aksk-kvfp.json?%24select=count%28*%29+as+cnt",
      "rowCount": 1,
      "coveredCount": 20773,
      "ms": 2647
    },
    {
      "label": "311 Service Requests - Pot Holes Reported - Historical — profiled, no time dimension",
      "url": "https://data.cityofchicago.org/resource/7as2-ds3y.json?%24select=count%28*%29+as+cnt",
      "rowCount": 1,
      "coveredCount": 560478,
      "ms": 4752
    },
    {
      "label": "Census Data - Selected socioeconomic indicators in Chicago, 2008 – 2012 — profiled, no time dimension",
      "url": "https://data.cityofchicago.org/resource/kn9c-c2s2.json?%24select=count%28*%29+as+cnt",
      "rowCount": 1,
      "coveredCount": 78,
      "ms": 514
    },
    {
      "label": "FOIA Request Log - Zoning and Land Use Planning - Historical — profiled, no time dimension",
      "url": "https://data.cityofchicago.org/resource/2nra-kpzu.json?%24select=count%28*%29+as+cnt",
      "rowCount": 1,
      "coveredCount": 414,
      "ms": 1145
    },
    {
      "label": "Chicago Street Names — profiled, no time dimension",
      "url": "https://data.cityofchicago.org/resource/i6bp-fvbx.json?%24select=count%28*%29+as+cnt",
      "rowCount": 1,
      "coveredCount": 2582,
      "ms": 205
    },
    {
      "label": "311 Service Requests - Street Lights - All Out - Historical — profiled, no time dimension",
      "url": "https://data.cityofchicago.org/resource/zuxi-7xem.json?%24select=count%28*%29+as+cnt",
      "rowCount": 1,
      "coveredCount": 296673,
      "ms": 718
    },
    {
      "label": "Financial Incentive Projects - Neighborhood Opportunity Fund (NOF) Small — profiled, no time dimension",
      "url": "https://data.cityofchicago.org/resource/rym7-49n8.json?%24select=count%28*%29+as+cnt",
      "rowCount": 1,
      "coveredCount": 126,
      "ms": 2108
    },
    {
      "label": "CTA - Ridership - Daily Boarding Totals, trailing 12mo (aggregate)",
      "url": "https://data.cityofchicago.org/resource/6iiy-9s97.json?%24select=count%28*%29+as+cnt&%24where=service_date+between+%272025-07-31T00%3A00%3A00%27+and+%272026-07-31T00%3A00%3A00%27",
      "rowCount": 1,
      "coveredCount": 366,
      "ms": 265
    },
    {
      "label": "CTA - Ridership - Daily Boarding Totals, prior 12mo (aggregate)",
      "url": "https://data.cityofchicago.org/resource/6iiy-9s97.json?%24select=count%28*%29+as+cnt&%24where=service_date+between+%272024-07-31T00%3A00%3A00%27+and+%272025-07-31T00%3A00%3A00%27",
      "rowCount": 1,
      "coveredCount": 0,
      "ms": 1184
    },
    {
      "label": "Financial Incentive Projects - Neighborhood Opportunity Fund (NOF) Large — profiled, no time dimension",
      "url": "https://data.cityofchicago.org/resource/j7ew-b73u.json?%24select=count%28*%29+as+cnt",
      "rowCount": 1,
      "coveredCount": 6,
      "ms": 490
    },
    {
      "label": "CTA - List of CTA Datasets — profiled, no time dimension",
      "url": "https://data.cityofchicago.org/resource/pnau-cf66.json?%24select=count%28*%29+as+cnt",
      "rowCount": 1,
      "coveredCount": 20,
      "ms": 276
    },
    {
      "label": "Performance Metrics - Business Affairs & Consumer Protection - Business Licenses — profiled, no time dimension",
      "url": "https://data.cityofchicago.org/resource/emvs-38e6.json?%24select=count%28*%29+as+cnt",
      "rowCount": 1,
      "coveredCount": 2564,
      "ms": 776
    },
    {
      "label": "Affordable Rental Housing Developments — profiled, no time dimension",
      "url": "https://data.cityofchicago.org/resource/s6ha-ppgi.json?%24select=count%28*%29+as+cnt",
      "rowCount": 1,
      "coveredCount": 598,
      "ms": 805
    },
    {
      "label": "Speed Camera Locations — profiled, no time dimension",
      "url": "https://data.cityofchicago.org/resource/4i42-qv3h.json?%24select=count%28*%29+as+cnt",
      "rowCount": 1,
      "coveredCount": 209,
      "ms": 848
    },
    {
      "label": "Financial Incentive Projects - Property Tax Abatement — profiled, no time dimension",
      "url": "https://data.cityofchicago.org/resource/syk7-tkvr.json?%24select=count%28*%29+as+cnt",
      "rowCount": 1,
      "coveredCount": 191,
      "ms": 370
    },
    {
      "label": "311 Service Requests - Tree Trims - Historical — profiled, no time dimension",
      "url": "https://data.cityofchicago.org/resource/uxic-zsuj.json?%24select=count%28*%29+as+cnt",
      "rowCount": 1,
      "coveredCount": 362957,
      "ms": 851
    }
  ],
  "whatWeMissed": {
    "datasetsNotPulled": [
      {
        "dataset": "Current Employee Names, Salaries, and Position Titles",
        "id": "xzkq-xp2w",
        "query": "https://data.cityofchicago.org/resource/xzkq-xp2w.json"
      },
      {
        "dataset": "Business Licenses - Current Active",
        "id": "uupf-x98q",
        "query": "https://data.cityofchicago.org/resource/uupf-x98q.json"
      },
      {
        "dataset": "Budget - 2011 Budget Ordinance - Appropriations",
        "id": "drv3-jzqp",
        "query": "https://data.cityofchicago.org/resource/drv3-jzqp.json"
      },
      {
        "dataset": "Budget - 2012 Budget Ordinance - Appropriations",
        "id": "8ix6-nb7q",
        "query": "https://data.cityofchicago.org/resource/8ix6-nb7q.json"
      },
      {
        "dataset": "COVID-19 Cases, Tests, and Deaths by ZIP Code - Historical",
        "id": "yhhz-zm2v",
        "query": "https://data.cityofchicago.org/resource/yhhz-zm2v.json"
      },
      {
        "dataset": "Energy Usage 2010",
        "id": "8yq3-m6wp",
        "query": "https://data.cityofchicago.org/resource/8yq3-m6wp.json"
      },
      {
        "dataset": "Building Violations",
        "id": "22u3-xenr",
        "query": "https://data.cityofchicago.org/resource/22u3-xenr.json"
      },
      {
        "dataset": "Tax Increment Financing (TIF) Funded RDA and IGA Projects",
        "id": "mex4-ppfc",
        "query": "https://data.cityofchicago.org/resource/mex4-ppfc.json"
      },
      {
        "dataset": "Current Employee Names, Salaries, and Position Titles - Full-time",
        "id": "n4bx-5kf6",
        "query": "https://data.cityofchicago.org/resource/n4bx-5kf6.json"
      },
      {
        "dataset": "Workforce Centers",
        "id": "cs4s-nsna",
        "query": "https://data.cityofchicago.org/resource/cs4s-nsna.json"
      }
    ],
    "lowEvidenceAreas": [],
    "note": "Cross-dataset geo joins, ownership identity resolution across name variants, and a Cerebras fallback for role inference (heuristics-only this run) are not in this run for Chicago — see next steps. Frozen datasets found: COVID-19 Daily Rolling Average Case, Death, and Hospitalization Rates - Historical, 311 Service Requests - Vacant and Abandoned Buildings Reported - Historical, COVID-19 Vaccinations by ZIP Code - Historical, Violence Reduction - Shotspotter Alerts - Historical, COVID-19 Daily Vaccinations - Chicago Residents - Historical."
  },
  "monitorChecksRun": 0,
  "reviewChecksRun": 5,
  "closingNote": "Complete — 1.2 min on Chicago (data.cityofchicago.org). Checklist not fully cleared. 60:00 was the ceiling, not the target.",
  "selfCheck": {
    "frozenDatasetCatch": "not yet computed — no stale dataset probe has run in this session",
    "review": {
      "unchanged": 5,
      "revised": 0,
      "unrecheckable": 0,
      "total": 5,
      "missedList": [
        {
          "dataset": "Current Employee Names, Salaries, and Position Titles",
          "id": "xzkq-xp2w",
          "query": "https://data.cityofchicago.org/resource/xzkq-xp2w.json"
        },
        {
          "dataset": "Business Licenses - Current Active",
          "id": "uupf-x98q",
          "query": "https://data.cityofchicago.org/resource/uupf-x98q.json"
        },
        {
          "dataset": "Budget - 2011 Budget Ordinance - Appropriations",
          "id": "drv3-jzqp",
          "query": "https://data.cityofchicago.org/resource/drv3-jzqp.json"
        },
        {
          "dataset": "Budget - 2012 Budget Ordinance - Appropriations",
          "id": "8ix6-nb7q",
          "query": "https://data.cityofchicago.org/resource/8ix6-nb7q.json"
        },
        {
          "dataset": "COVID-19 Cases, Tests, and Deaths by ZIP Code - Historical",
          "id": "yhhz-zm2v",
          "query": "https://data.cityofchicago.org/resource/yhhz-zm2v.json"
        },
        {
          "dataset": "Energy Usage 2010",
          "id": "8yq3-m6wp",
          "query": "https://data.cityofchicago.org/resource/8yq3-m6wp.json"
        },
        {
          "dataset": "Building Violations",
          "id": "22u3-xenr",
          "query": "https://data.cityofchicago.org/resource/22u3-xenr.json"
        },
        {
          "dataset": "Tax Increment Financing (TIF) Funded RDA and IGA Projects",
          "id": "mex4-ppfc",
          "query": "https://data.cityofchicago.org/resource/mex4-ppfc.json"
        },
        {
          "dataset": "Current Employee Names, Salaries, and Position Titles - Full-time",
          "id": "n4bx-5kf6",
          "query": "https://data.cityofchicago.org/resource/n4bx-5kf6.json"
        },
        {
          "dataset": "Workforce Centers",
          "id": "cs4s-nsna",
          "query": "https://data.cityofchicago.org/resource/cs4s-nsna.json"
        }
      ],
      "lowEv": []
    }
  },
  "progress": [],
  "checklist": [
    {
      "id": "geography",
      "label": "Neighborhood: every real geographic unit in Chicago profiled",
      "done": true
    },
    {
      "id": "economic",
      "label": "Economic: a verified finding tying a $/% move to a named place",
      "done": false
    },
    {
      "id": "government",
      "label": "Government: a cross-record-type or service-load finding",
      "done": false
    },
    {
      "id": "business_opportunity",
      "label": "Business opportunity: a site-selection-grade finding",
      "done": false
    },
    {
      "id": "discoveries",
      "label": "Discoveries: an unasked-for finding (e.g. a frozen dataset)",
      "done": true
    },
    {
      "id": "what_missed",
      "label": "Self-critique: what we missed, from this run's real gaps",
      "done": true
    },
    {
      "id": "review",
      "label": "Review: every finding re-checked against live data",
      "done": true
    }
  ],
  "milestones": {
    "firstSource": 221,
    "firstVerifiedFinding": 28328,
    "checklist_discoveries": 28549,
    "fullCompletion": 71270
  },
  "changeSinceLastRun": {
    "hasPrevious": true,
    "previousRunId": "aedcf90b",
    "previousAt": 1790651812136,
    "added": [],
    "removed": [
      {
        "id": "generic-stale-f3he-c6sv",
        "title": "Dataset found but frozen: COVID-19 Hospital Capacity Metrics - Historical",
        "mission": "discoveries"
      },
      {
        "id": "generic-owner-ezma-pppn",
        "title": "Business Owners: concentration — top named entity holds 83 records",
        "mission": "discoveries"
      }
    ],
    "changed": []
  }
};
